# Generated by Django 3.2.7 on 2021-09-16 10:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(editable=False, max_length=128, region=None, verbose_name='phone')),
                ('otp', models.CharField(editable=False, max_length=40, verbose_name='otp')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('attempts', models.IntegerField(default=0, verbose_name='attempts')),
                ('used', models.BooleanField(default=False, verbose_name='used')),
            ],
            options={
                'verbose_name': 'otp token',
                'verbose_name_plural': 'otp tokens',
                'db_table': 'phone_token',
            },
        ),
    ]
