# Generated by Django 3.2.7 on 2021-09-20 09:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0004_auto_20210920_0856'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlevote',
            unique_together={('user', 'article')},
        ),
    ]
